export const ITEM_META = {
    // ═══════════ Primaries ═══════════

    // Assault Rifles
    PRI_LIBERATOR: {
        display_name: "AR-23 Liberator",
        slot: "primary",
        pen: "light",
        warbond: "Base",
        tags: ["rifle"],
    },
    PRI_LIBERATOR_PEN: {
        display_name: "AR-23P Liberator Penetrator",
        slot: "primary",
        pen: "medium",
        warbond: "Helldivers Mobilize",
        tags: ["rifle"],
    },
    PRI_LIBERATOR_CONC: {
        display_name: "AR-23C Liberator Concussive",
        slot: "primary",
        pen: "light",
        warbond: "Steeled Veterans",
        tags: ["rifle"],
    },
    PRI_STA_ASS_RIFLE: {
        display_name: "StA-52 Assault Rifle",
        slot: "primary",
        pen: "light",
        warbond: "Superstore",
        tags: ["rifle"],
    },
    PRI_PACIFIER: {
        display_name: "AR-32 Pacifier",
        slot: "primary",
        pen: "medium",
        warbond: "Force of Law",
        tags: ["rifle", "stun"],
    },
    PRI_COYOTE: {
        display_name: "AR-2 Coyote",
        slot: "primary",
        pen: "medium",
        warbond: "Dust Devils",
        tags: ["rifle", "incendiary"],
    },
    PRI_MAC5_ASS_RIFLE: {
        display_name: "MA5C Assault Rifle (MAC-5)",
        slot: "primary",
        pen: "medium",
        warbond: "ODST",
        tags: ["rifle"],
    },
    PRI_LIBERATOR_CARB: {
        display_name: "AR-23A Liberator Carbine",
        slot: "primary",
        pen: "light",
        warbond: "Viper Commandos",
        tags: ["rifle"],
    },
    PRI_TENDERIZER: {
        display_name: "AR-61 Tenderizer",
        slot: "primary",
        pen: "light",
        warbond: "Polar Patriots",
        tags: ["rifle"],
    },
    PRI_ADJUDICATOR: {
        display_name: "BR-14 Adjudicator",
        slot: "primary",
        pen: "medium",
        warbond: "Democratic Detonation",
        tags: ["rifle"],
    },
    PRI_ONETWO: {
        display_name: "AR/GL-21 One-Two",
        slot: "primary",
        pen: "medium",
        warbond: "Python Commandos",
        tags: ["rifle", "grenade_launcher"],
    },
    PRI_SUPPRESSOR: {
        display_name: "AR-59 Suppressor",
        slot: "primary",
        pen: "light",
        warbond: "Unknown",
        tags: ["rifle"],
    },

    // Marksman Rifles
    PRI_AMENDMENT: {
        display_name: "R-2 Amendment",
        slot: "primary",
        pen: "light",
        warbond: "Masters of Ceremony",
        tags: ["marksman", "rifle", "melee"],
    },
    PRI_CONSTITUTION: {
        display_name: "R-2124 Constitution",
        slot: "primary",
        pen: "medium",
        warbond: "Event",
        tags: ["marksman", "rifle", "melee"],
    },
    PRI_DEADEYE: {
        display_name: "R-6 Deadeye",
        slot: "primary",
        pen: "medium",
        warbond: "Borderline Justice",
        tags: ["marksman", "rifle", "roundsreload"],
    },
    PRI_DILLIGENCE: {
        display_name: "R-63 Diligence",
        slot: "primary",
        pen: "light",
        warbond: "Helldivers Mobilize",
        tags: ["marksman", "rifle"],
    },
    PRI_DILLIGENCE_CS: {
        display_name: "R-63CS Diligence Counter Sniper",
        slot: "primary",
        pen: "light",
        warbond: "Helldivers Mobilize",
        tags: ["marksman", "rifle"],
    },
    PRI_CENSOR: {
        display_name: "R-72 Censor",
        slot: "primary",
        pen: "light",
        warbond: "Unknown",
        tags: ["marksman", "rifle"],
    },

    // SMGs
    PRI_KNIGHT: {
        display_name: "MP-98 Knight",
        slot: "primary",
        pen: "light",
        warbond: "Super Citizen Edition",
        tags: ["smg", "onehanded"],
    },
    PRI_STA_SMG: {
        display_name: "StA-11 SMG",
        slot: "primary",
        pen: "light",
        warbond: "Superstore",
        tags: ["smg", "onehanded"],
    },
    PRI_M7S_SMG: {
        display_name: "M7S SMG",
        slot: "primary",
        pen: "light",
        warbond: "ODST",
        tags: ["smg", "onehanded"],
    },
    PRI_REPRIMAND: {
        display_name: "SMG-32 Reprimand",
        slot: "primary",
        pen: "medium",
        warbond: "Truth Enforcers",
        tags: ["smg"],
    },
    PRI_DEFENDER: {
        display_name: "SMG-37 Defender",
        slot: "primary",
        pen: "light",
        warbond: "Helldivers Mobilize",
        tags: ["smg", "one_handed"],
    },
    PRI_PUMMELER: {
        display_name: "SMG-72 Pummeller",
        slot: "primary",
        pen: "light",
        warbond: "Polar Patriots",
        tags: ["smg", "concussive"],
    },

    // Shotguns
    PRI_PUNISHER: {
        display_name: "SG-8 Punisher",
        slot: "primary",
        pen: "light",
        warbond: "Helldivers Mobilize",
        tags: ["shotgun", "roundsreload"],
    },
    PRI_SLUGGER: {
        display_name: "SG-8S Slugger",
        slot: "primary",
        pen: "medium",
        warbond: "Helldivers Mobilize",
        tags: ["shotgun", "roundsreload"],
    },
    PRI_HALT: {
        display_name: "SG-20 Halt",
        slot: "primary",
        pen: "medium",
        warbond: "Truth Enforcers",
        tags: ["shotgun", "stun", "roundsreload"],
    },
    PRI_COOKOUT: {
        display_name: "SG-451 Cookout",
        slot: "primary",
        pen: "light",
        warbond: "Freedom's Flame",
        tags: ["shotgun", "incendiary", "roundsreload"],
    },
    PRI_DOUBLE_FREEDOM: {
        display_name: "DBS-2 Double Freedom",
        slot: "primary",
        pen: "medium",
        warbond: "Unknown",
        tags: ["shotgun"],
    },
    PRI_M90A_SGUN: {
        display_name: "M90A Shotgun",
        slot: "primary",
        pen: "light",
        warbond: "ODST",
        tags: ["shotgun", "roundsreload"],
    },
    PRI_BREAKER: {
        display_name: "SG-225 Breaker",
        slot: "primary",
        pen: "light",
        warbond: "Helldivers Mobilize",
        tags: ["shotgun"],
    },
    PRI_BREAKER_SPNPR: {
        display_name: "SG-225SP Breaker Spray & Pray",
        slot: "primary",
        pen: "light",
        warbond: "Helldivers Mobilize",
        tags: ["shotgun"],
    },
    PRI_BREAKER_INCIN: {
        display_name: "SG-225IE Breaker Incendiary",
        slot: "primary",
        pen: "light",
        warbond: "Steeled Veterans",
        tags: ["shotgun", "incendiary"],
    },

    // Energy / Laser / Plasma
    PRI_SCYTHE_LAS: {
        display_name: "LAS-5 Scythe",
        slot: "primary",
        pen: "light",
        warbond: "Cutting Edge",
        tags: ["laser", "beam", "heat"],
    },
    PRI_SICKLE_LAS: {
        display_name: "LAS-16 Sickle",
        slot: "primary",
        pen: "light",
        warbond: "Cutting Edge",
        tags: ["laser", "rifle", "heat"],
    },
    PRI_DOUBLE_EDGE_SICKLE: {
        display_name: "LAS-17 Double-Edge Sickle",
        slot: "primary",
        pen: "heavy",
        warbond: "Servants of Freedom",
        tags: ["laser", "self_damage", "heat"],
    },
    PRI_SCORCHER_PLAS: {
        display_name: "PLAS-1 Scorcher",
        slot: "primary",
        pen: "medium",
        warbond: "Helldivers Mobilize",
        tags: ["plasma", "explosive"],
    },
    PRI_PURIFIER_PLAS: {
        display_name: "PLAS-101 Purifier",
        slot: "primary",
        pen: "medium",
        warbond: "Polar Patriots",
        tags: ["plasma", "explosive"],
    },
    PRI_PUNISHER_PLAS: {
        display_name: "SG-8P Punisher Plasma",
        slot: "primary",
        pen: "medium",
        warbond: "Cutting Edge",
        tags: ["shotgun", "plasma", "explosive"],
    },
    PRI_ACCELERATOR_RIFLE: {
        display_name: "LAS-39 Accelerator Rifle",
        slot: "primary",
        pen: "medium",
        warbond: "Event",
        tags: ["energy", "rifle"],
    },
    PRI_BLITZER: {
        display_name: "ARC-12 Blitzer",
        slot: "primary",
        pen: "medium",
        warbond: "Cutting Edge",
        tags: ["shotgun", "energy", "electric", "infinite ammo"],
    },
    PRI_TRIDENT: {
        display_name: "LAS-13 Trident",
        slot: "primary",
        pen: "light",
        warbond: "Siege Breakers",
        tags: ["shotgun", "energy", "electric"],
    },

    // Special Weapons
    PRI_VARIABLE: {
        display_name: "VG-70 Variable",
        slot: "primary",
        pen: "light",
        warbond: "Control Group",
        tags: ["togglemode", "rifle", "shotgun"],
    },
    PRI_TORCHER_FLAM: {
        display_name: "FLAM-66 Torcher",
        slot: "primary",
        pen: "heavy",
        warbond: "Freedom's Flame",
        tags: ["flamethrower", "incendiary"],
    },
    PRI_JAR_DOMINATOR: {
        display_name: "JAR-5 Dominator",
        slot: "primary",
        pen: "medium",
        warbond: "Steeled Veterans",
        tags: ["marksman", "explosive"],
    },
    PRI_EXPLODING_XBOW: {
        display_name: "CB-9 Exploding Crossbow",
        slot: "primary",
        pen: "medium",
        warbond: "Democratic Detonation",
        tags: ["explosive", "crossbow"],
    },
    PRI_ERUPTOR: {
        display_name: "R-36 Eruptor",
        slot: "primary",
        pen: "heavy",
        warbond: "Democratic Detonation",
        tags: ["explosive", "marksman", "roundsreload"],
    },

    // ═══════════ Secondaries ═══════════

    SEC_WARRANT: {
        display_name: "P-92 Warrant",
        slot: "secondary",
        pen: "medium",
        warbond: "Superstore",
        tags: ["pistol", "guided"],
    },
    SEC_PEACEMAKER: {
        display_name: "P-2 Peacemaker",
        slot: "secondary",
        pen: "light",
        warbond: "Base",
        tags: ["pistol"],
    },
    SEC_REDEEMER: {
        display_name: "P-19 Redeemer",
        slot: "secondary",
        pen: "light",
        warbond: "Helldivers Mobilize",
        tags: ["pistol", "auto"],
    },
    SEC_VERDICT: {
        display_name: "P-113 Verdict",
        slot: "secondary",
        pen: "medium",
        warbond: "Polar Patriots",
        tags: ["pistol"],
    },
    SEC_SOCOM_PISTOL: {
        display_name: "SOCOM Pistol",
        slot: "secondary",
        pen: "light",
        warbond: "ODST",
        tags: ["pistol", "supressed"],
    },
    SEC_SENATOR: {
        display_name: "P-4 Senator",
        slot: "secondary",
        pen: "heavy",
        warbond: "Steeled Veterans",
        tags: ["pistol", "revolver", "rounds reload"],
    },
    SEC_STUN_LANCE: {
        display_name: "CQC-19 Stun Lance",
        slot: "secondary",
        pen: "medium",
        warbond: "Urban Legends",
        tags: ["melee", "stun"],
    },
    SEC_SABER: {
        display_name: "CQC-2 Saber",
        slot: "secondary",
        pen: "medium",
        warbond: "Masters of Ceremony",
        tags: ["melee"],
    },
    SEC_STUN_BATON: {
        display_name: "CQC-30 Stun Baton",
        slot: "secondary",
        pen: "medium",
        warbond: "Superstore",
        tags: ["melee", "stun"],
    },
    SEC_HATCHET: {
        display_name: "CQC-9 Hatchet",
        slot: "secondary",
        pen: "medium",
        warbond: "Superstore",
        tags: ["melee"],
    },
    SEC_MACHETE: {
        display_name: "CQC-16 Machete",
        slot: "secondary",
        pen: "medium",
        warbond: "Superstore",
        tags: ["melee"],
    },
    SEC_STIM_PISTOL: {
        display_name: "Stim Pistol",
        slot: "secondary",
        pen: "none",
        warbond: "Chemical Agents",
        tags: ["utility", "stim"],
    },
    SEC_BUSHWACKER: {
        display_name: "SG-22 Bushwhacker",
        slot: "secondary",
        pen: "light",
        warbond: "Viper Commandos",
        tags: ["shotgun", "one_handed"],
    },
    SEC_TALON: {
        display_name: "LAS-58 Talon",
        slot: "secondary",
        pen: "medium",
        warbond: "Borderline Justice",
        tags: ["laser", "pistol"],
    },
    SEC_CRISPER: {
        display_name: "P-72 Crisper",
        slot: "secondary",
        pen: "medium",
        warbond: "Freedom's Flame",
        tags: ["flamethrower"],
    },
    SEC_GRENADE_PISTOL: {
        display_name: "GP-31 Grenade Pistol",
        slot: "secondary",
        pen: "medium",
        warbond: "Democratic Detonation",
        tags: ["explosive", "grenade_launcher"],
    },
    SEC_DAGGER_LAS: {
        display_name: "LAS-7 Dagger",
        slot: "secondary",
        pen: "light",
        warbond: "Cutting Edge",
        tags: ["laser", "beam"],
    },
    SEC_ULTIMATUM: {
        display_name: "GP-31 Ultimatum",
        slot: "secondary",
        pen: "heavy",
        warbond: "Servants of Freedom",
        tags: ["explosive", "grenade_launcher"],
    },
    SEC_LOYALIST: {
        display_name: "PLAS-15 Loyalist",
        slot: "secondary",
        pen: "medium",
        warbond: "Truth Enforcers",
        tags: ["plasma"],
    },
    SEC_RE_EDUCATOR: {
        display_name: "P-35 Re-Educator",
        slot: "secondary",
        pen: "heavy",
        warbond: "Unknown",
        tags: ["pistol"],
    },

    // ═══════════ Grenades / Throwables ═══════════

    THR_DYNAMITE: {
        display_name: "TED-63 Dynamite",
        slot: "grenade",
        pen: "none",
        warbond: "Borderline Justice",
        tags: ["explosive", "timed"],
    },
    THR_FRAG: {
        display_name: "G-6 Frag",
        slot: "grenade",
        pen: "none",
        warbond: "Base",
        tags: ["frag", "explosive"],
    },
    THR_HIGH_EXPLOSIVE: {
        display_name: "G-12 High Explosive",
        slot: "grenade",
        pen: "none",
        warbond: "Base",
        tags: ["explosive"],
    },
    THR_INCENDIARY: {
        display_name: "G-10 Incendiary",
        slot: "grenade",
        pen: "none",
        warbond: "Base",
        tags: ["incendiary"],
    },
    THR_PINEAPPLE: {
        display_name: "G-7 Pineapple",
        slot: "grenade",
        pen: "none",
        warbond: "Dust Devils",
        tags: ["frag", "cluster"],
    },
    THR_IMPACT: {
        display_name: "G-16 Impact",
        slot: "grenade",
        pen: "none",
        warbond: "Helldivers Mobilize",
        tags: ["impact", "explosive"],
    },
    THR_INCENDIARY_IMPACT: {
        display_name: "G-13 Incendiary Impact",
        slot: "grenade",
        pen: "none",
        warbond: "Polar Patriots",
        tags: ["incendiary", "impact"],
    },
    THR_STUN: {
        display_name: "G-23 Stun",
        slot: "grenade",
        pen: "none",
        warbond: "Base",
        tags: ["stun"],
    },
    THR_GAS: {
        display_name: "G-3 Gas",
        slot: "grenade",
        pen: "none",
        warbond: "Chemical Agents",
        tags: ["gas"],
    },
    THR_SEEKER: {
        display_name: "G-50 Seeker",
        slot: "grenade",
        pen: "none",
        warbond: "Unknown",
        tags: ["seeker"],
    },
    THR_SMOKE: {
        display_name: "G-9 Smoke",
        slot: "grenade",
        pen: "none",
        warbond: "Base",
        tags: ["smoke"],
    },
    THR_THERMITE: {
        display_name: "G-123 Thermite",
        slot: "grenade",
        pen: "none",
        warbond: "Chemical Agents",
        tags: ["thermite", "incendiary"],
    },
    THR_THROWING_KNIFE: {
        display_name: "Throwing Knife",
        slot: "grenade",
        pen: "none",
        warbond: "Unknown",
        tags: ["knife", "thrown"],
    },
    THR_PYROTECH: {
        display_name: "G-142 Pyrotech",
        slot: "grenade",
        pen: "none",
        warbond: "Masters of Ceremony",
        tags: ["incendiary", "fireworks"],
    },
    THR_URCHIN: {
        display_name: "G-109 Urchin",
        slot: "grenade",
        pen: "none",
        warbond: "Force of Law",
        tags: ["stun", "sticky"],
    },
    THR_ARC: {
        display_name: "G-31 Arc",
        slot: "grenade",
        pen: "none",
        warbond: "Unknown",
        tags: ["electric"],
    },
    THR_LURE_MINE: {
        display_name: "TM-1 Lure Mine",
        slot: "grenade",
        pen: "none",
        warbond: "Unknown",
        tags: ["mine", "utility"],
    },
    THR_SMOKESCREEN: {
        display_name: "G-89 Smokescreen",
        slot: "grenade",
        pen: "none",
        warbond: "Unknown",
        tags: ["smoke"],
    },
    THR_SHIELD: {
        display_name: "G/SH-39 Shield",
        slot: "grenade",
        pen: "none",
        warbond: "Unknown",
        tags: ["shield", "utility"],
    },
};
